### ISSUE TITLE
no control states

### ISSUE THREAD

**Issue by lug-gh** [JoJ123/ioBroker.mihome-airpurifier#13] opened 2019-03-04 20:44 UTC
I paired my air purifier 2s with this adapter, infos work fine, but I can't control it, as there are no control options..

![image](https://user-images.githubusercontent.com/24546639/53761696-7215f880-3ec6-11e9-9732-d7512bc4cf30.png)

miio discover:
```
Model info: zhimi.airpurifier.ma2
Support: At least basic
```

any ideas?

**Comment by lug-gh** [comment] 2019-03-04 20:46
Well, I added power manually and then everything else appeared..

**Comment by JoJ123** [comment] 2019-04-07 12:58
I can't reproduce this and you fixed it by your own, I will close this issue now :)

**Closed by JoJ123** 2019-04-07 12:58 UTC
